"""Final_PINN_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXQ0zUobSK6Mz4kU-qooZ1sKeZ3n8dk5

# Environment setup
"""

"""
LSTM-PINN Battery SOH Prediction
Step 1: Environment Setup & Imports

Run this cell first in Google Colab
"""

# ========================================
# 1.1: Install Required Packages
# ========================================
print("📦 Installing required packages...")
print("=" * 70)

# PyTorch (if not already installed)
import subprocess
try:
    import torch
    print(f"✓ PyTorch already installed: v{torch.__version__}")
except ImportError:
    print("Installing PyTorch...")
    subprocess.run("pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118", shell=True)

# Additional packages (usually pre-installed in Colab)
subprocess.run("pip install -q tqdm pandas numpy matplotlib scikit-learn", shell=True)

print("✓ All packages installed\n")


# ========================================
# 1.2: Import Libraries
# ========================================
print("📚 Importing libraries...")
print("=" * 70)

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
from tqdm.auto import tqdm
import pickle
import warnings
from typing import Tuple, Dict, List, Optional
import time
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

print("✓ All libraries imported\n")


# ========================================
# 1.3: Check Hardware Configuration
# ========================================
print("🖥️  Hardware Configuration:")
print("=" * 70)

# Check CUDA availability
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

if device == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    gpu_memory = torch.cuda.get_device_properties(0).total_memory / (1024**3)
    print(f"GPU Memory: {gpu_memory:.2f} GB")
    print(f"CUDA Version: {torch.version.cuda}")
else:
    print("⚠️  GPU not available - will use CPU (slower)")
    print("   To enable GPU: Runtime > Change runtime type > GPU")

# Check PyTorch version
print(f"PyTorch Version: {torch.__version__}")
#print(f"Python Version: {import sys; sys.version.split()[0]}" if 'sys' in dir() else "")

print("\n✓ Hardware check complete\n")


# ========================================
# 1.4: Mount Google Drive
# ========================================
print("📁 Mounting Google Drive...")
print("=" * 70)

from google.colab import drive

try:
    # Mount drive (will prompt for authorization first time)
    drive.mount('/content/drive', force_remount=False)
    print("✓ Google Drive mounted successfully")

    # Verify drive is accessible
    drive_path = Path('/content/drive/MyDrive')
    if drive_path.exists():
        print(f"✓ Drive accessible at: {drive_path}")
    else:
        print("⚠️  Warning: MyDrive not found at expected path")

except Exception as e:
    print(f"❌ Error mounting drive: {e}")
    print("Please authorize Google Drive access when prompted")
    raise

print()


# ========================================
# 1.5: Verify Data Directory Structure
# ========================================
print("🔍 Verifying data directory...")
print("=" * 70)

# Expected data path
data_path = Path('/content/drive/MyDrive/data')

if not data_path.exists():
    print(f"❌ Data directory not found at: {data_path}")
    print("\n📝 Please ensure your data is organized as:")
    print("   /content/drive/MyDrive/data/")
    print("       ├── metadata.csv")
    print("       ├── 0001.csv")
    print("       ├── 0002.csv")
    print("       └── ... (7,567 cycle files)")
    print("\n💡 If your data is in a different location, update the path above")

    # Ask user to confirm path
    print("\n" + "=" * 70)
    print("ACTION REQUIRED:")
    print("1. Create folder: /content/drive/MyDrive/data/")
    print("2. Upload metadata.csv and all cycle CSV files")
    print("3. Re-run this cell")
    print("=" * 70)

else:
    print(f"✓ Data directory found: {data_path}")

    # Check for metadata.csv
    metadata_path = data_path / 'metadata.csv'
    if metadata_path.exists():
        print(f"✓ metadata.csv found")

        # Quick peek at metadata structure
        try:
            df = pd.read_csv(metadata_path, nrows=5)
            print(f"✓ Metadata readable ({len(pd.read_csv(metadata_path))} rows)")
            print(f"\n   Columns: {list(df.columns)}")
            print(f"\n   First few rows:")
            print(df.head(3).to_string(index=False))
        except Exception as e:
            print(f"⚠️  Warning: Could not read metadata.csv: {e}")
    else:
        print(f"❌ metadata.csv NOT found at {metadata_path}")

    # Count CSV files
    csv_files = list(data_path.glob('*.csv'))
    cycle_files = [f for f in csv_files if f.name != 'metadata.csv']
    print(f"\n✓ Found {len(cycle_files)} cycle CSV files")

    if len(cycle_files) > 0:
        print(f"   Sample files: {', '.join([f.name for f in cycle_files[:5]])}")
        if len(cycle_files) > 5:
            print(f"   ... and {len(cycle_files) - 5} more")

    # Check expected number
    if len(cycle_files) < 7000:
        print(f"\n⚠️  Expected ~7,567 files, found only {len(cycle_files)}")
        print("   This may be normal if some files haven't been uploaded yet")

print()


# ========================================
# 1.6: Configuration Setup
# ========================================
print("⚙️  Setting up configuration...")
print("=" * 70)

# Global configuration dictionary
CONFIG = {
    # Paths
    'data_dir': data_path,
    'output_dir': Path('/content/outputs'),

    # Data preprocessing
    'rated_capacity': 2.0,      # Battery rated capacity in Ah
    'sequence_length': 20,      # Number of historical cycles to use
    'min_cycles': 50,          # Minimum cycles per battery

    # Model architecture
    'lstm_hidden': 256,
    'lstm_layers': 2,
    'physics_hidden': 256,
    'physics_layers': 3,

    # Training parameters
    'batch_size': 32,
    'epochs': 200,
    'learning_rate': 0.001,

    # Loss weights
    'lambda_pred': 1.0,
    'lambda_pde': 0.1,
    'lambda_grad': 0.01,

    # Hardware
    'device': device,
    'num_workers': 2,
}

# Create output directory
CONFIG['output_dir'].mkdir(exist_ok=True)
print(f"✓ Output directory: {CONFIG['output_dir']}")

print("\n📋 Configuration:")
for key, value in CONFIG.items():
    if key not in ['data_dir', 'output_dir']:
        print(f"   {key}: {value}")

print()


# ========================================
# 1.7: Save Configuration
# ========================================
print("💾 Saving configuration...")
print("=" * 70)

config_path = CONFIG['output_dir'] / 'config.pkl'
with open(config_path, 'wb') as f:
    pickle.dump(CONFIG, f)

print(f"✓ Configuration saved to: {config_path}")

print()


# ========================================
# SETUP COMPLETE
# ========================================
print("=" * 70)
print("✅ STEP 1 COMPLETE: Environment Setup")
print("=" * 70)
print("\n📌 Summary:")
print(f"   ✓ Device: {device}")
print(f"   ✓ Data directory: {data_path}")
print(f"   ✓ Output directory: {CONFIG['output_dir']}")
print(f"   ✓ Configuration saved")

if data_path.exists() and (data_path / 'metadata.csv').exists():
    print("\n✅ Ready to proceed to Step 2: Data Preprocessing")
    print("\n💡 Next: Run the Step 2 cell to load and preprocess battery data")
else:
    print("\n⚠️  Action Required:")
    print("   Please ensure metadata.csv and cycle files are in:")
    print(f"   {data_path}")
    print("\n   Then re-run this cell before proceeding")

print("\n" + "=" * 70)
